pool:
  vmImage: 'ubuntu-latest' 

stages:
  - stage: Build
    jobs:
      - job: Build_Job
        steps:
          - task: Maven@3 
            inputs:
              mavenVersionOption: 'Default'
              mavenPomFile: 'pom.xml' 
              goals: 'clean package'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/target'
              artifactName: 'maven-artifacts'
              publishLocation: 'Pipeline'
